stages:
  - build
  - test

build-app:
  stage: build
  image: tinkoff-edu-app:1.0.0
  script:
    - cd spring-petclinic-rest
    - ./mvnw package
    - java -jar target/*.jar

tests:
  stage: test
  image: tinkoff-edu-app:1.0.0
  script:
    - mvn clean test
  after_script:
    - '[ ! -d "public" ] && mkdir public'
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - public

